$(document).ready(function(){
	$('#n1').click(function(){
		$('#dc1').show();
		$('#dc2').hide();
		$('#dc3').hide();
		$('#dc4').hide();
		$('#dc5').hide();
		$('#dc6').hide();
		$('#dc7').hide();

	});
	$('#n2').click(function(){
		$('#dc1').hide();
		$('#dc2').show();
		$('#dc3').hide();
		$('#dc4').hide();
		$('#dc5').hide();
		$('#dc6').hide();
		$('#dc7').hide();
	});
	$('#n3').click(function(){
		$('#dc1').hide();
		$('#dc2').hide();
		$('#dc3').show();
		$('#dc4').hide();
		$('#dc5').hide();
		$('#dc6').hide();
		$('#dc7').hide();
	});
	$('#n4').click(function(){
		$('#dc1').hide();
		$('#dc2').hide();
		$('#dc3').hide();
		$('#dc4').show();
		$('#dc5').hide();
		$('#dc6').hide();
		$('#dc7').hide();
	});
	$('#n5').click(function(){
		$('#dc1').hide();
		$('#dc2').hide();
		$('#dc3').hide();
		$('#dc4').hide();
		$('#dc5').show();
		$('#dc6').hide();
		$('#dc7').hide();
	});
	$('#n6').click(function(){
		$('#dc1').hide();
		$('#dc2').hide();
		$('#dc3').hide();
		$('#dc4').hide();
		$('#dc5').hide();
		$('#dc6').show();
		$('#dc7').hide();
	});
	$('#n7').click(function(){
		$('#dc1').hide();
		$('#dc2').hide();
		$('#dc3').hide();
		$('#dc4').hide();
		$('#dc5').hide();
		$('#dc6').hide();
		$('#dc7').show();
	});
});